### ISSUE TITLE
🛑 URLs for files are not resolving

### ISSUE THREAD

**Issue by biosimulations-daemon** [biosimulations/status-monitor#2]
In [`6895ba2`](https://github.com/biosimulations/status-monitor/commit/6895ba24941eb22fa536217dcf7ad4ed654f39cf
), Storage Buckets (https://files.biosimulations.org/s3/helloWorld.txt) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by bilalshaikh42** [comment]
URLs for the files stored on the backend are not connecting properly. This prevents some features such as uploading a combine archive to start a simulation to fail. 

Using a URL that points to a combine archive instead provides a workaround

**Comment by bilalshaikh42** [comment]
Server Rebooted
