### ISSUE TITLE
🛑 Combine Simulation API is down

### ISSUE THREAD

**Issue by biosimulations-daemon** [biosimulations/status-monitor#5]
In [`3ebb35f`](https://github.com/biosimulations/status-monitor/commit/3ebb35f33dd0c7a89bc9858e682e2db53fd0f352
), Combine Simulation API (https://combine.api.biosimulations.org/run/simulators) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by bilalshaikh42** [comment]
This seems to be caused by the slow start mentioned in https://github.com/biosimulations/Biosimulations/issues/2848
